### ISSUE TITLE
snippets don't respect tab size and "translate to spaces" settings

### ISSUE THREAD

**Issue by rwols** [Phidica/sublime-fish#12]
In the snippet files, all snippets that apply an indentation indent with 2 spaces. If you use a tab character for the indent, Sublime will automatically translate that to 4 spaces, or tabs, or whatever. Right now I have my settings set to 4 spaces + translate tabs to spaces, but inserting a snippet gives me a 2 space indent.

Also it's probably a good idea to organize those snippet files in a subfolder `snippets`.

**Comment by Phidica** [comment]
Ahh of course, I didn't think about that. I'll fix them up
