### ISSUE TITLE
equals sign inside command substitution breaks highlighting

### ISSUE THREAD

**Issue by rwols** [Phidica/sublime-fish#13]
The following snippet shows that the closing parenthesis is not recognized:
```
#!/usr/bin/env fish
set result (echo a = b)
echo $result
```
From here: https://github.com/gcuisinier/jenv/blob/master/fish/export.fish

**Comment by Phidica** [comment]
Are you still using version 2.1.1, by any chance? I cannot reproduce this bug, with either of your examples, on any version between 2.1.2 and 2.2.3 (the latest, as available through Package Control)

**Comment by rwols** [comment]
It seems I had an old master branch! Sorry for the noise :)
