### ISSUE TITLE
"end" at the end of file is not highlighted correctly

### ISSUE THREAD

**Issue by vvolhejn** [Phidica/sublime-fish#15]
Consider the code
```fish
if true
end
```

(without a newline after `end`). Then `end` is highlighted as if it were a command name rather than a keyword; in Monokai, blue instead of red.

In other syntax highlighters (try the same code highlighted like MATLAB), this behaves as expected.

**Comment by Phidica** [comment]
Ah, thank you for pointing this out. I use ST with the "ensure_newline_at_eof_on_save" setting enabled, so I hadn't noticed this. The syntax almost exclusively looks for `\n` to end scopes, rather than `$` which is all that would be present at the end of the file... I'll take a look

**Comment by vvolhejn** [comment]
Thanks! I have newline-on-save as well, but it was a bit annoying before
saving.
