### ISSUE TITLE
conflicts with default shell script syntax

### ISSUE THREAD

**Issue by nhooyr** [Phidica/sublime-fish#18]
See https://github.com/sublimehq/Packages/blob/289782ff2e4cb58de171579c7fc86fe00d280619/ShellScript/Bash.sublime-syntax#L16

Not sure if there is a way to make this plugin override that as the default everywhere.

**Comment by rwols** [comment]
Hi Anmol, that file extension existed in the syntax from way back. However, the default shell script syntax does not support fish anymore. Maybe you can make a pull request to remove it?

**Comment by nhooyr** [comment]
Will do.

**Comment by nhooyr** [comment]
See https://github.com/sublimehq/Packages/pull/1664

**Comment by Phidica** [comment]
Thanks for submitting the upstream pull request. I'll close this issue if it gets accepted otherwise we can return to the original question of making this package override

**Comment by Phidica** [comment]
I just noticed that PR was merged, so I believe that closes this issue
