### ISSUE TITLE
[fish 3] && and || highlighted wrong

### ISSUE THREAD

**Issue by floam** [Phidica/sublime-fish#20]
The newish `&&` and `||` fish 3 syntax is causing the remainder of the line to be highlighted like a syntax error.

**Comment by Phidica** [comment]
Yes, fish 3 currently isn't supported and I haven't yet decided how I'm going to go about it. 

There are several backwards incompatible changes (such as removed support for `^` redirection and `?` globbing) between the syntaxes. Currently I'm considering adapting this repository to provide separate packages on Package Control for fish 2 and fish 3. Do any users have a preference between me continuing to support fish 2 in this way, or retaining just one package that only supports the latest version of fish?

If I go down the route of having two packages, then the current package would become "fish 2" and users would need to uninstall that and install a "fish 3" package to upgrade fish versions.

**Comment by floam** [comment]
Could you detect the installed version of fish at runtime? There will be fish 2 users for a while yet.

**Comment by Phidica** [comment]
Ohh, that's a great idea actually. The package can distribute both syntax files and a plugin can automatically detect which one to apply based on the user's fish version.

**Comment by PatrickF1** [comment]
Hi @Phidica , first off big thanks for maintaining this package. I use fish frequently and I love ST3 so I am very fan of your package. Could you give us an update on fish 3 support, please?

**Comment by Phidica** [comment]
The main obstruction has been the conversion to .sublime-syntax, which I want to be coincident with the release of fish 3 support. I've recently picked this conversion work back up after taking some time away from it to consider my path forward.

fish 3 support is certainly coming, I would say within the next few months but I can't be more specific or committal than that.

**Comment by Phidica** [comment]
Closed with the release of 3.0.0 :tada: Sorry for the long delay in getting it done, but I hope it has been worth the wait :)

**Comment by PatrickF1** [comment]
Thank you @Phidica ! Very much appreciate your volunteer effort in maintaining this awesome package!
