### ISSUE TITLE
Stderr redirect append operator `^^` and deprecation warnings

### ISSUE THREAD

**Issue by lwolfsonkin** [Phidica/sublime-fish#23]
I found that the stderr redirect append operator `^^` (which is like `>>` but for redirecting stderr instead of stdout) gets a deprecation message suggesting you replace it with `2>`, but I believe that since this is an append operator, `2>>` would be the appropriate replacement.

The current behavior is misleading and can lead to people accidentally introducing changes in the logic of their fish scripts.

Thanks so much for maintaining this awesome package! It's super useful!

**Comment by Phidica** [comment]
Thank you for the kind words, and for catching this oversight! You're quite right that the hint on resolving deprecated append operators should be changed. I'm going to prioritise this so I can fix it hopefully before anyone breaks any of their scripts.
