### ISSUE TITLE
Highlight issue

### ISSUE THREAD

**Issue by dnicolson** [Phidica/sublime-fish#3]
The following code results the last `end` being highlighted the full width of the document:

```
function my_func
  begin
    echo "hi"
  end; or begin
    echo "hi again"
  end
end
```
<img width="289" alt="screen shot 2017-08-14 at 16 09 27" src="https://user-images.githubusercontent.com/2276355/29275321-0e81ea74-810b-11e7-8834-85e2b7e6bb57.png">

**Comment by Phidica** [comment]
Hi! Thanks for the report. I suspect this issue stems from a continuing problem I've had with properly treating `begin ... end` as a sort of grouped command which could appear anywhere a normal command could. I've been thinking of solutions, and I believe I have one for this bug, but I've been a little too busy lately to work on this project. I'll try and find some time soon to work through this and other matters in #2

**Comment by Phidica** [comment]
Actually it was a little easier than I'd thought. But it happened because I have been drawing a distinction between blocks and command calls, even though the former is an instance of the latter. I will probably revise this at some point
