### ISSUE TITLE
Add to packagecontrol

### ISSUE THREAD

**Issue by madblobfish** [Phidica/sublime-fish#4]
Could you add this as a package to packagecontrol?
That would make finding it more easy and probably bring some users to it.
Another bonus is more comfortable installation and deinstallation, thanks.

packagecontrol docs: https://packagecontrol.io/docs/submitting_a_package

**Comment by Phidica** [comment]
Ah yes, I was planning on submitting a package eventually, but had decided to hold off until the syntax was feature-complete. I didn't want to present the syntax as entirely functional when, in my opinion, it has some problems as it stands right now (mostly around piping and its interaction with blocks)

I have been doing a lot of local development lately to try and iron out those problems, but perhaps it is time I push the commits to a dev branch for those who want them and share the syntax in its current stable-but-incomplete form...

Thanks for prompting me about this :) I will see about submitting a package in the next few days

**Comment by Phidica** [comment]
I've pushed my `block-rewrite` branch to the repo so I can be held accountable for the work going on over there, but I have decided to hold off on submitting a package until I merge `block-rewrite` (and its ongoing rewrites of major scopes) into `master`. The reason for this is that I plan to make that merge my first major release. Hopefully in the next week or so I will be done with this development and can submit the package

**Comment by madblobfish** [comment]
Thanks, I'm looking forward to the release.

**Comment by Phidica** [comment]
I've made the submission to Package Control, you can track its progress [in the pull request](https://github.com/wbond/package_control_channel/pull/6670)

**Comment by Phidica** [comment]
Merged 🎉

**Comment by madblobfish** [comment]
Thanks :)
