### ISSUE TITLE
Pipe symbol not always getting correct scope

### ISSUE THREAD

**Issue by rwols** [Phidica/sublime-fish#6]
```
make fish 2>| less
#         ^^^ pipe stderr to stdin of "less"
```

**Comment by Phidica** [comment]
This is fixed in the current development branch "block-rewrite" (which
overhauled piping particularly around blocks but also for this case) and I
will in fact be merging it into master this evening :)

**Comment by Phidica** [comment]
These changes are now in master, marking as fixed
